dist: trusty

language: scala

env:
  - TRAVIS_JDK=8

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install:
  - jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
  - nvm install 7.9.0

script: sbt +test
